run:
  delivery: False

# paths
workspace_path: 'results'

dest_path: 'destination'
sum_stat_path: '/exchange/healthds/pQTL/results/META_CHRIS_INTERVAL/qced_sumstats_digits_not_flipped/output'
cojo_results: '/exchange/healthds/pQTL/results/META_CHRIS_INTERVAL/qced_sumstats_digits_not_flipped_filtered/16-Dec-24_collected_independent_snps.csv'
mapping_filepath: '/exchange/healthds/pQTL/Reference_datasets_for_QC_proteomics/Cis_trans_mapping/somascan_tss_ncbi_grch37_ensembl_version_20241216.txt'
locus_breaker_filepath: '/exchange/healthds/pQTL/results/META_CHRIS_INTERVAL/qced_sumstats_digits_not_flipped_filtered/16-Dec-24_collected_loci_excluding_mhc.csv'
chain_file: '/group/diangelantonio/public_data/liftOver/hg19ToHg38.over.chain.gz'
hg37_fasta_file: '/group/diangelantonio/public_data/liftOver/human_g1k_v37.fasta'
hg37_fasta_fai_file: '/group/diangelantonio/public_data/liftOver/human_g1k_v37.fasta.fai'
hg38_fasta_file: '/group/diangelantonio/public_data/liftOver/hg38.fa'
hg38_fasta_fai_file: '/group/diangelantonio/public_data/liftOver/hg38.fa.fai'
array_list_path: "data/"

params:
  nef: 3978
  Isquare: 90