executor: slurm
jobs: 250
software-deployment-method:
   - conda
   - apptainer
retries: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
cores: &cores 2
latency-wait: 60
keep-going: True
rerun-incomplete: False
printshellcmds: True
scheduler: ilp

default-resources:
    slurm_partition: cpuq
    # slurm_account: ${USER}
    mem_mb: attempt * 512
    threads: 1
    runtime: attempt * 5
set-resources:
    select_best_SNP_from_LocusBreaker:
        mem_mb: 2048 + attempt * 2048
        threads: *cores
    heterogenous_filter:
        mem_mb: 2048 + attempt * 2048
        threads: *cores
    LB_liftover_ivs:
        mem_mb: 2048 + attempt * 2048
        threads: *cores
    select_SNP_from_cojo:
      mem_mb: 2048 + attempt * 2048
      threads: *cores
    vcf_file_LB:
      mem_mb: 2048 + attempt * 2048
      threads: *cores
    bcftools_liftover_LB:
      mem_mb: 2048 + attempt * 2048
      threads: *cores
    LB_liftover_ivs:
      mem_mb: 2048 + attempt * 2048
      threads: *cores
    vcf_file_cojo:
      mem_mb: 2048 + attempt * 2048
      threads: *cores
    bcftools_liftover_cojo:
      mem_mb: 2048 + attempt * 2048
      threads: *cores





